#!/bin/bash

sudo apt update -y;
sudo apt full-upgrade -y;
sudo apt install -y wget vlc espeak;
sudo apt autoremove -y;
curl -sS https://get.pimoroni.com/speakerphat | bash;
pip install --upgrade pip;
pip install -r requirements.txt;
